# Generated by Django 3.0.8 on 2021-06-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20210618_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='unordered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('W', 'Waiting'), ('P', 'Preparing'), ('S', 'SENDING'), ('D', 'Done')], default='W', max_length=1)),
                ('is_accepted', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Food')),
            ],
        ),
    ]
