# Generated by Django 3.0.8 on 2021-06-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20210618_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='unordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='food',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.ManyToManyField(default=None, to='managers.Order'),
        ),
    ]
