# Generated by Django 3.0.8 on 2021-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20210620_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.SmallIntegerField(default=0),
        ),
    ]
