# Generated by Django 3.0.8 on 2021-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0013_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='start',
        ),
        migrations.AddField(
            model_name='order',
            name='now',
            field=models.TimeField(auto_now=True),
        ),
    ]
