# Generated by Django 3.0.8 on 2021-06-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit'),
        ('managers', '0014_auto_20210622_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=140, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Food')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
