# Generated by Django 3.0.8 on 2021-06-17 13:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, validators=[accounts.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[accounts.validators.PhoneValidator()]),
        ),
    ]
