# Generated by Django 3.0.8 on 2021-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.IntegerField(default=1000000),
        ),
    ]
